version: "3"

services:
  application:
    image: ashokit/springboot-mysql-app
    ports:
      - 8080:8080
    networks:
      - springboot-nw
    depends_on:
      - mysqldb
    volumes:
     - /data/springboot-app
  mysqldb:
    image: mysql:5.7
    networks:
      - springboot-nw
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sbms
    volumes:
    - data/mysql

networks:
  springboot-nw: