apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebappbluedeploy
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: java-web-app
      version: v1
      color: blue
  template:
    metadata:
      name: java-web
      labels:
        app: java-web-app
        version: v1
        color: blue
  spec:
    containers:
    - name: java-web-app-container
      image: ashokit/javawebapp
      imagePullPolicy: always
      ports:
      - containerPort: 8080
