apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebappbluedeploy
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: java-web-app
      version: v2
      color: green
  template:
    metadata:
      name: java-web
      labels:
        app: java-web-app
        version: v2
        color: green
    spec:
      containers:
      - name: java-web-app-container
        image: lakshjain1/lakshnginx
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
