apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebdeploy
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: javaweb
  template:
    metadata:
      name: javaweb
      labels:
        app: javaweb
    spec:
      containers:
      - name: javawebcontainer
        image: ashokit/javawebapp
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: javawebSVC
spec:
  type: NodePort
  selector:
    app: javaweb
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30785
