apiVersion: v1
kind: Pod
metadata:
  name: javaweb
  labels:
    app: javawebapp #very important for service
spec:
  containers:
  - name: javawebappcontainer
    image: ashokit/javawebapp
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: javawebsrv
spec:
  type: LoadBalancer
  selector:
    app: javawebapp #POD label
  ports:
  - port: 80
    targetPort: 8080
