apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: javawebrs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: javaweb
  template:
    metadata:
      name: javawebapp
      labels:
        app: javaweb
    spec:
      containers:
      - name: javawebappcontainer
        image: ashokit/javawebapp
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: javawebsvc
spec:
  type: NodePort
  selector:
    app: javaweb
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30678
